use crate::spec::ApiSpec;
use crate::traits::{GeneratedOutput, LanguageGenerator};

pub struct RustGenerator;

impl LanguageGenerator for RustGenerator {
    fn target(&self) -> &str {
        "rust"
    }

    fn file_extension(&self) -> &str {
        "rs"
    }

    fn generate(&self, spec: &ApiSpec) -> GeneratedOutput {
        let mut files = Vec::new();

        files.push(("Cargo.toml".into(), generate_cargo_toml(spec)));
        files.push(("src/lib.rs".into(), generate_lib_rs(spec)));
        files.push(("src/models.rs".into(), generate_models(spec)));
        files.push(("src/parser.rs".into(), generate_parser(spec)));
        files.push(("src/client.rs".into(), generate_client(spec)));
        files.push(("src/error.rs".into(), generate_error(spec)));

        GeneratedOutput { files }
    }
}

fn pascal_case(s: &str) -> String {
    s.split('_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

fn crate_name(spec: &ApiSpec) -> String {
    spec.name.to_lowercase().replace(' ', "-").replace('_', "-")
}

fn client_name(spec: &ApiSpec) -> String {
    format!("{}Client", pascal_case(&spec.name))
}

fn error_name(spec: &ApiSpec) -> String {
    format!("{}Error", pascal_case(&spec.name))
}

fn newtype_names(spec: &ApiSpec) -> Vec<String> {
    spec.types
        .iter()
        .filter(|(_, m)| m.newtype.unwrap_or(false))
        .map(|(name, _)| name.clone())
        .collect()
}

fn is_newtype(spec: &ApiSpec, type_name: &str) -> bool {
    spec.types
        .get(type_name)
        .map(|m| m.newtype.unwrap_or(false))
        .unwrap_or(false)
}

fn is_enum_type(type_name: &str, spec: &ApiSpec) -> bool {
    spec.enums.contains_key(type_name)
}

fn is_entity_type(type_name: &str, spec: &ApiSpec) -> bool {
    spec.entities.contains_key(type_name)
}

fn resolve_type(type_name: &str, nullable: bool, spec: &ApiSpec) -> String {
    // Handle Option<X> — resolve the inner type and wrap back
    if type_name.starts_with("Option<") && type_name.ends_with('>') {
        let inner = &type_name[7..type_name.len() - 1];
        let resolved_inner = resolve_type_raw(inner, spec);
        return format!("Option<{}>", resolved_inner);
    }

    let resolved = resolve_type_raw(type_name, spec);

    if nullable && !resolved.starts_with("Option") {
        format!("Option<{}>", resolved)
    } else {
        resolved
    }
}

fn resolve_type_raw(type_name: &str, spec: &ApiSpec) -> String {
    if spec.enums.contains_key(type_name) || spec.entities.contains_key(type_name) {
        return type_name.to_string();
    }

    if let Some(tm) = spec.types.get(type_name) {
        if tm.newtype.unwrap_or(false) {
            return type_name.to_string();
        }
        if let Some(rust) = &tm.rust {
            return rust.clone();
        }
    }

    match type_name {
        "string" => "String".to_string(),
        "decimal" | "f64" => "f64".to_string(),
        "u32" => "u32".to_string(),
        "bool" => "bool".to_string(),
        "date" | "datetime" => "Option<String>".to_string(),
        "url" => "String".to_string(),
        other => other.to_string(),
    }
}

fn is_numeric_type(type_name: &str, spec: &ApiSpec) -> bool {
    if let Some(tm) = spec.types.get(type_name) {
        if let Some(rust) = &tm.rust {
            return matches!(rust.as_str(), "f64" | "u32" | "i64" | "u64");
        }
    }
    matches!(type_name, "f64" | "u32" | "i64" | "u64" | "Price")
}

fn is_bool_type(type_name: &str) -> bool {
    type_name == "bool"
}

fn is_vec_type(type_name: &str) -> bool {
    type_name.starts_with("Vec<")
}

fn enum_match_arm(variant: &str, enum_name: &str) -> String {
    let camel = pascal_case(variant);
    format!("\"{}\" => Some({}::{})", variant, enum_name, camel)
}

// ── Cargo.toml ──────────────────────────────────────────────────────

fn generate_cargo_toml(spec: &ApiSpec) -> String {
    let name = crate_name(spec);
    format!(
        r#"# @generated by specgen — DO NOT EDIT
# Source: {} v{}

[package]
name = "{}-sdk"
version = "0.1.0"
edition = "2021"
description = "Auto-generated SDK for {}"
license = "MIT"

[dependencies]
reqwest = {{ version = "0.12", features = ["json", "cookies", "rustls-tls"] }}
scraper = "0.22"
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"
tokio = {{ version = "1", features = ["full"] }}
thiserror = "2"
log = "0.4"

[dev-dependencies]
tokio = {{ version = "1", features = ["full", "test-util"] }}
"#,
        spec.name, spec.version, name, spec.name
    )
}

// ── lib.rs ──────────────────────────────────────────────────────────

fn generate_lib_rs(_spec: &ApiSpec) -> String {
    r#"// @generated by specgen — DO NOT EDIT

pub mod models;
pub mod parser;
pub mod client;
pub mod error;
"#
    .to_string()
}

// ── models.rs ───────────────────────────────────────────────────────

fn generate_models(spec: &ApiSpec) -> String {
    let mut o = String::from("// @generated by specgen — DO NOT EDIT\n\n");
    o.push_str("use serde::{Deserialize, Serialize};\nuse std::hash::Hash;\n\n");

    let newtypes = newtype_names(spec);
    if !newtypes.is_empty() {
        o.push_str(&generate_newtypes_block(spec));
        o.push('\n');
    }

    for (name, enum_def) in &spec.enums {
        o.push_str(&format!(
            "#[derive(Debug, Clone, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]\npub enum {} {{\n",
            name
        ));
        let mut first = true;
        for (variant, _) in &enum_def.values {
            let camel = pascal_case(variant);
            if first {
                o.push_str(&format!(
                    "    #[default]\n    #[serde(rename = \"{}\")]\n    {},\n",
                    variant, camel
                ));
                first = false;
            } else {
                o.push_str(&format!(
                    "    #[serde(rename = \"{}\")]\n    {},\n",
                    variant, camel
                ));
            }
        }
        o.push_str("}\n\n");

        o.push_str(&format!("impl std::fmt::Display for {} {{\n", name));
        o.push_str("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n");
        o.push_str("        match self {\n");
        for (variant, _) in &enum_def.values {
            let camel = pascal_case(variant);
            o.push_str(&format!(
                "            {}::{} => write!(f, \"{}\"),\n",
                name, camel, variant
            ));
        }
        o.push_str("        }\n");
        o.push_str("    }\n}\n\n");
    }

    for (name, entity) in &spec.entities {
        if let Some(fields) = &entity.fields {
            o.push_str(&format!(
                "#[derive(Debug, Clone, Serialize, Deserialize)]\npub struct {} {{\n",
                name
            ));
            for (field_name, field_def) in fields {
                let rust_type = resolve_type(&field_def.r#type, field_def.nullable.unwrap_or(false), spec);
                o.push_str(&format!("    pub {}: {},\n", field_name, rust_type));
            }
            o.push_str("}\n\n");
        }
    }

    o
}

fn generate_newtypes_block(spec: &ApiSpec) -> String {
    let mut o = String::new();
    o.push_str(
        r#"pub trait IdType: std::fmt::Display + std::str::FromStr + Clone + Copy + PartialEq + Eq + Hash {
    fn new(id: u64) -> Self;
    fn inner(self) -> u64;
}

macro_rules! define_id_type {
    ($name:ident) => {
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]
        pub struct $name(u64);

        impl $name {
            pub fn new(id: u64) -> Self { Self(id) }
            pub fn inner(self) -> u64 { self.0 }
        }

        impl std::fmt::Display for $name {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "{}", self.0)
            }
        }

        impl std::str::FromStr for $name {
            type Err = std::num::ParseIntError;
            fn from_str(s: &str) -> Result<Self, Self::Err> { Ok(Self(s.parse()?)) }
        }
    };
}

"#,
    );

    for (name, tm) in &spec.types {
        if !tm.newtype.unwrap_or(false) {
            continue;
        }
        let rust_type = tm.rust.as_deref().unwrap_or("u64");
        if rust_type == "u64" || rust_type == "u32" {
            o.push_str(&format!("define_id_type!({});\n", name));
        } else {
            let (extra_derives, extra_impls) = if rust_type == "f64" {
                (
                    "",
                    r#"
impl Default for NAME {
    fn default() -> Self { Self(0.0) }
}

impl std::str::FromStr for NAME {
    type Err = std::num::ParseFloatError;
    fn from_str(s: &str) -> Result<Self, Self::Err> { Ok(Self(s.parse()?)) }
}
"#,
                )
            } else {
                (
                    ", Eq, Hash",
                    r#"
impl std::str::FromStr for NAME {
    type Err = std::string::ParseError;
    fn from_str(s: &str) -> Result<Self, Self::Err> { Ok(Self(s.to_string())) }
}
"#,
                )
            };
            let impls = extra_impls.replace("NAME", name);
            o.push_str(&format!(
                "#[derive(Debug, Clone, PartialEq{}, Serialize, Deserialize)]\npub struct {}(pub {});\n\nimpl {} {{\n    pub fn new(v: impl Into<{}>) -> Self {{ Self(v.into()) }}\n    pub fn inner(&self) -> &{} {{ &self.0 }}\n}}\n\nimpl std::fmt::Display for {} {{\n    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{\n        write!(f, \"{{}}\", self.0)\n    }}\n}}\n{}\n",
                extra_derives, name, rust_type, name, rust_type, rust_type, name, impls
            ));
        }
    }

    o
}

// ── parser.rs ───────────────────────────────────────────────────────

fn generate_parser(spec: &ApiSpec) -> String {
    let mut o = String::from("// @generated by specgen — DO NOT EDIT\n\n");
    o.push_str("use scraper::{Html, Selector};\nuse crate::models::*;\n\n");
    o.push_str(
        r#"fn extract_text(el: &scraper::ElementRef, selector: &str) -> Option<String> {
    let sel = Selector::parse(selector).ok()?;
    el.select(&sel).next()?.text().next().map(|s| s.trim().to_string())
}

fn extract_attr(el: &scraper::ElementRef, selector: &str, attr: &str) -> Option<String> {
    let sel = Selector::parse(selector).ok()?;
    el.select(&sel).next()?.value().attr(attr).map(|s| s.to_string())
}

pub struct Parser;

impl Parser {
    pub fn new() -> Self { Self }
"#,
    );

    for (page_name, page_def) in &spec.pages {
        let entity_name = &page_def.entity;
        if let Some(entity) = spec.entities.get(entity_name) {
            if let Some(fields) = &entity.fields {
                if let Some(list_selector) = &page_def.list_selector {
                    o.push_str(&format!(
                        "    pub fn parse_{}(&self, html: &str) -> Vec<{}> {{\n",
                        page_name, entity_name
                    ));
                    o.push_str("        let document = Html::parse_document(html);\n");
                    o.push_str(&format!(
                        "        let selector = Selector::parse(\"{}\").unwrap();\n",
                        list_selector
                    ));
                    o.push_str("        document.select(&selector)\n");
                    o.push_str("            .filter_map(|el| {\n");

                    for (field_name, field_def) in fields {
                        let is_optional = field_def.nullable.unwrap_or(false)
                            || field_def.r#type.starts_with("Option<");
                        let extraction =
                            generate_extraction(field_name, field_def, is_optional, spec);
                        o.push_str(&format!("                {}\n", extraction));
                    }

                    o.push_str(&format!("                Some({} {{\n", entity_name));
                    for (field_name, field_def) in fields {
                        let conv = generate_conversion(field_name, &field_def.r#type, spec);
                        if conv.is_empty() {
                            o.push_str(&format!("                    {},\n", field_name));
                        } else if conv.starts_with('.') {
                            o.push_str(&format!(
                                "                    {}: {}{},\n",
                                field_name, field_name, conv
                            ));
                        } else {
                            o.push_str(&format!(
                                "                    {}: {},\n",
                                field_name, conv
                            ));
                        }
                    }
                    o.push_str("                })\n");
                    o.push_str("            })\n");
                    o.push_str("            .collect()\n");
                    o.push_str("    }\n\n");
                }
            }
        }
    }

    for (page_name, page_def) in &spec.pages {
        let entity_name = &page_def.entity;
        if let Some(entity) = spec.entities.get(entity_name) {
            if let Some(fields) = &entity.fields {
                if page_def.list_selector.is_none() {
                    o.push_str(&format!(
                        "    pub fn parse_{}(&self, html: &str) -> Option<{}> {{\n",
                        page_name, entity_name
                    ));
                    o.push_str("        let document = Html::parse_document(html);\n");
                    o.push_str("        let el = document.root_element();\n");

                    for (field_name, field_def) in fields {
                        let is_optional = field_def.nullable.unwrap_or(false)
                            || field_def.r#type.starts_with("Option<");
                        let extraction =
                            generate_extraction(field_name, field_def, is_optional, spec);
                        o.push_str(&format!("        {}\n", extraction));
                    }

                    o.push_str(&format!("        Some({} {{\n", entity_name));
                    for (field_name, field_def) in fields {
                        let conv = generate_conversion(field_name, &field_def.r#type, spec);
                        if conv.is_empty() {
                            o.push_str(&format!("            {},\n", field_name));
                        } else if conv.starts_with('.') {
                            o.push_str(&format!(
                                "            {}: {}{},\n",
                                field_name, field_name, conv
                            ));
                        } else {
                            o.push_str(&format!(
                                "            {}: {},\n",
                                field_name, conv
                            ));
                        }
                    }
                    o.push_str("        })\n");
                    o.push_str("    }\n\n");
                }
            }
        }
    }

    o.push_str("}\n");
    o
}

fn generate_extraction(
    field_name: &str,
    field_def: &crate::spec::FieldDef,
    is_optional: bool,
    spec: &ApiSpec,
) -> String {
    let raw_type = &field_def.r#type;
    let inner_type = if raw_type.starts_with("Option<") && raw_type.ends_with('>') {
        &raw_type[7..raw_type.len() - 1]
    } else {
        raw_type.as_str()
    };

    if is_vec_type(inner_type) {
        return format!("let {} = Vec::new();", field_name);
    }
    if is_entity_type(inner_type, spec) {
        if let Some(entity) = spec.entities.get(inner_type) {
            if let Some(fields) = &entity.fields {
                let field_inits: Vec<String> = fields
                    .iter()
                    .map(|(fname, fdef)| {
                        let ftype = &fdef.r#type;
                        if is_newtype(spec, ftype) {
                            format!("{}: {}::new(0)", fname, ftype)
                        } else if ftype == "u32" {
                            format!("{}: 0u32", fname)
                        } else if ftype == "f64" || is_numeric_type(ftype, spec) {
                            format!("{}: 0.0", fname)
                        } else if is_bool_type(ftype) {
                            format!("{}: false", fname)
                        } else if is_enum_type(ftype, spec) {
                            format!("{}: Default::default()", fname)
                        } else if ftype == "String" {
                            format!("{}: String::new()", fname)
                        } else if is_vec_type(ftype) {
                            format!("{}: Vec::new()", fname)
                        } else if ftype.starts_with("Option<") {
                            format!("{}: None", fname)
                        } else {
                            format!("{}: Default::default()", fname)
                        }
                    })
                    .collect();
                return format!(
                    "let {} = {} {{ {} }};",
                    field_name,
                    inner_type,
                    field_inits.join(", ")
                );
            }
        }
        return format!("let {} = {} {{}};", field_name, inner_type);
    }

    let needs_enum_conv = is_enum_type(inner_type, spec);
    let needs_id_conv = is_newtype(spec, inner_type);
    let needs_num_conv = is_numeric_type(inner_type, spec);
    let needs_bool_conv = is_bool_type(inner_type);
    let needs_conversion =
        needs_enum_conv || needs_id_conv || needs_num_conv || needs_bool_conv;

    if let Some(attr) = &field_def.attribute {
        if let Some(sel) = &field_def.selector {
            if needs_conversion || is_optional {
                format!(
                    "let {} = extract_attr(&el, \"{}\", \"{}\");",
                    field_name, sel, attr
                )
            } else {
                format!(
                    "let {} = extract_attr(&el, \"{}\", \"{}\").unwrap_or_default();",
                    field_name, sel, attr
                )
            }
        } else if needs_conversion || is_optional {
            format!(
                "let {} = el.value().attr(\"{}\").map(|s| s.to_string());",
                field_name, attr
            )
        } else {
            format!(
                "let {} = el.value().attr(\"{}\").map(|s| s.to_string()).unwrap_or_default();",
                field_name, attr
            )
        }
    } else if let Some(sel) = &field_def.selector {
        if needs_conversion || is_optional {
            format!("let {} = extract_text(&el, \"{}\");", field_name, sel)
        } else {
            format!(
                "let {} = extract_text(&el, \"{}\").unwrap_or_default();",
                field_name, sel
            )
        }
    } else if is_optional {
        format!("let {}: Option<String> = None;", field_name)
    } else {
        format!("let {} = String::new();", field_name)
    }
}

fn generate_conversion(_field_name: &str, field_type: &str, spec: &ApiSpec) -> String {
    if field_type.starts_with("Option<") && field_type.ends_with('>') {
        let inner = &field_type[7..field_type.len() - 1];
        if is_enum_type(inner, spec) {
            if let Some(enum_def) = spec.enums.get(inner) {
                let arms: Vec<String> = enum_def
                    .values
                    .keys()
                    .map(|v| enum_match_arm(v, inner))
                    .collect();
                return format!(
                    ".and_then(|s| match s.as_str() {{ {}, _ => None }})",
                    arms.join(", ")
                );
            }
        }
        if is_newtype(spec, inner) {
            return format!(".and_then(|s| s.parse::<{}>().ok())", inner);
        }
        if is_numeric_type(inner, spec) {
            return format!(".and_then(|s| s.parse::<{}>().ok())", inner);
        }
        if is_entity_type(inner, spec) {
            return "None".to_string();
        }
        return String::new();
    }

    if is_vec_type(field_type) {
        return String::new();
    }

    if is_enum_type(field_type, spec) {
        if let Some(enum_def) = spec.enums.get(field_type) {
            let arms: Vec<String> = enum_def
                .values
                .keys()
                .map(|v| enum_match_arm(v, field_type))
                .collect();
            return format!(
                ".and_then(|s| match s.as_str() {{ {}, _ => None }}).unwrap_or_default()",
                arms.join(", ")
            );
        }
    }
    if is_newtype(spec, field_type) {
        return format!(
            ".and_then(|s| s.parse::<{}>().ok()).unwrap_or_default()",
            field_type
        );
    }
    if is_numeric_type(field_type, spec) {
        return format!(
            ".and_then(|s| s.parse::<{}>().ok()).unwrap_or_default()",
            field_type
        );
    }
    if is_bool_type(field_type) {
        return ".and_then(|s| s.parse::<bool>().ok()).unwrap_or_default()".to_string();
    }
    if is_entity_type(field_type, spec) {
        return String::new();
    }
    String::new()
}

// ── client.rs ───────────────────────────────────────────────────────

fn generate_client(spec: &ApiSpec) -> String {
    let err = error_name(spec);
    let client = client_name(spec);
    let base_url = spec.base_url.as_deref().unwrap_or("https://example.com");

    let mut o = String::from("// @generated by specgen — DO NOT EDIT\n\n");
    o.push_str(&format!(
        "use reqwest::Client;\nuse crate::error::{};\nuse crate::models::*;\nuse crate::parser::Parser;\n\n",
        err
    ));
    o.push_str(&format!("pub const DEFAULT_BASE_URL: &str = \"{}\";\n\n", base_url));
    o.push_str(&format!("pub struct {} {{\n", client));
    o.push_str("    pub client: Client,\n");
    o.push_str("    pub base_url: String,\n");
    o.push_str("}\n\n");

    o.push_str(&format!("impl {} {{\n", client));
    o.push_str(&format!("    pub fn new() -> Result<Self, {}> {{\n", err));
    o.push_str("        Self::with_base_url(DEFAULT_BASE_URL)\n");
    o.push_str("    }\n\n");

    o.push_str(&format!(
        "    pub fn with_base_url(base_url: &str) -> Result<Self, {}> {{\n",
        err
    ));
    o.push_str("        let client = Client::builder()\n");
    o.push_str("            .user_agent(\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36\")\n");
    o.push_str("            .cookie_store(true)\n");
    o.push_str("            .timeout(std::time::Duration::from_secs(30))\n");
    o.push_str("            .build()?;\n");
    o.push_str("        Ok(Self { client, base_url: base_url.to_string() })\n");
    o.push_str("    }\n\n");

    o.push_str(&format!(
        "    pub async fn get(&self, path: &str) -> Result<String, {}> {{\n",
        err
    ));
    o.push_str("        let url = if path.starts_with(\"http\") {\n");
    o.push_str("            path.to_string()\n");
    o.push_str("        } else {\n");
    o.push_str("            format!(\"{}{}\", self.base_url, path)\n");
    o.push_str("        };\n");
    o.push_str("        let resp = self.client.get(&url).send().await?;\n");
    o.push_str("        Ok(resp.text().await?)\n");
    o.push_str("    }\n\n");

    for (page_name, page_def) in &spec.pages {
        let entity_name = &page_def.entity;
        let url_pattern = page_def.url_pattern.as_ref().or(page_def.url.as_ref());

        if let Some(url_pattern) = url_pattern {
            let params: Vec<String> = {
                let mut params = Vec::new();
                let mut chars = url_pattern.chars().peekable();
                while let Some(c) = chars.next() {
                    if c == '{' {
                        let mut param = String::new();
                        while let Some(&nc) = chars.peek() {
                            if nc == '}' {
                                chars.next();
                                break;
                            }
                            param.push(nc);
                            chars.next();
                        }
                        params.push(param);
                    }
                }
                params
            };

            let params_str = if params.is_empty() {
                String::new()
            } else {
                params
                    .iter()
                    .map(|p| format!("{}: u64", p))
                    .collect::<Vec<_>>()
                    .join(", ")
            };

            let mut url_format = url_pattern.clone();
            for p in &params {
                url_format = url_format.replace(&format!("{{{}}}", p), "{}");
            }

            let is_list = page_def.list_selector.is_some();
            let return_type = if is_list {
                format!("Vec<{}>", entity_name)
            } else {
                entity_name.to_string()
            };

            let method_name = format!("fetch_{}", page_name);
            o.push_str(&format!(
                "    pub async fn {}(&self, {}) -> Result<{}, {}> {{\n",
                method_name, params_str, return_type, err
            ));

            if params.is_empty() {
                o.push_str(&format!(
                    "        let html = self.get(\"{}\").await?;\n",
                    url_pattern
                ));
            } else {
                o.push_str(&format!(
                    "        let html = self.get(&format!(\"{}\", {})).await?;\n",
                    url_format,
                    params.join(", ")
                ));
            }

            if is_list {
                o.push_str(&format!(
                    "        Ok(Parser::new().parse_{}(&html))\n",
                    page_name
                ));
            } else {
                o.push_str(&format!(
                    "        Parser::new().parse_{}(&html).ok_or_else(|| {}::Parse(crate::error::ParseError::MissingField(\"{}\".into())))\n",
                    page_name, err, entity_name
                ));
            }
            o.push_str("    }\n\n");
        }
    }

    o.push_str("}\n");
    o
}

// ── error.rs ────────────────────────────────────────────────────────

fn generate_error(spec: &ApiSpec) -> String {
    let err = error_name(spec);
    format!(
        r#"// @generated by specgen — DO NOT EDIT

use thiserror::Error;

#[derive(Debug, Error)]
pub enum ParseError {{
    #[error("missing data-app-data attribute")]
    NoDataAppData,
    #[error("unclosed data-app-data attribute")]
    UnclosedDataAppData,
    #[error("JSON parse error: {{0}}")]
    JsonParse(String),
    #[error("missing field: {{0}}")]
    MissingField(String),
}}

#[derive(Debug, Error)]
pub enum AuthError {{
    #[error("invalid golden key")]
    InvalidGoldenKey,
    #[error("CSRF token mismatch")]
    CsrfMismatch,
}}

#[derive(Debug, Error)]
pub enum {} {{
    #[error("HTTP error: {{0}}")]
    Http(#[from] reqwest::Error),
    #[error("parse error: {{0}}")]
    Parse(#[from] ParseError),
    #[error("auth error: {{0}}")]
    Auth(#[from] AuthError),
    #[error("rate limited, retry after {{0:?}}")]
    RateLimited(std::time::Duration),
    #[error("request timeout after {{0:?}}")]
    Timeout(std::time::Duration),
}}

pub type Result<T> = std::result::Result<T, {}>;
"#,
        err, err
    )
}
