use crate::spec::ApiSpec;
use crate::traits::{GeneratedOutput, LanguageGenerator};

pub struct TypeScriptGenerator;

impl LanguageGenerator for TypeScriptGenerator {
    fn target(&self) -> &str {
        "typescript"
    }

    fn file_extension(&self) -> &str {
        "ts"
    }

    fn generate(&self, spec: &ApiSpec) -> GeneratedOutput {
        let mut files = Vec::new();

        files.push(("package.json".into(), generate_package_json(spec)));
        files.push(("tsconfig.json".into(), generate_tsconfig(spec)));
        files.push(("src/types.ts".into(), generate_types(spec)));
        files.push(("src/models.ts".into(), generate_models(spec)));
        files.push(("src/parser.ts".into(), generate_parser(spec)));
        files.push(("src/client.ts".into(), generate_client(spec)));

        GeneratedOutput { files }
    }
}

fn pascal_case(s: &str) -> String {
    s.split('_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

fn camel_case(s: &str) -> String {
    let pascal = pascal_case(s);
    let mut chars = pascal.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_lowercase().collect::<String>() + chars.as_str(),
    }
}

fn package_name(spec: &ApiSpec) -> String {
    spec.name
        .to_lowercase()
        .replace(' ', "-")
        .replace('_', "-")
}

fn client_name(spec: &ApiSpec) -> String {
    format!("{}Client", pascal_case(&spec.name))
}

fn resolve_type_ts(type_name: &str, nullable: bool, spec: &ApiSpec) -> String {
    if type_name.starts_with("Option<") && type_name.ends_with('>') {
        let inner = &type_name[7..type_name.len() - 1];
        return resolve_type_ts(inner, false, spec);
    }

    if type_name.starts_with("Vec<") && type_name.ends_with('>') {
        let inner = &type_name[4..type_name.len() - 1];
        let resolved = resolve_type_ts(inner, false, spec);
        return format!("{}[]", resolved);
    }

    let resolved = if spec.enums.contains_key(type_name) || spec.entities.contains_key(type_name) {
        pascal_case(type_name)
    } else if let Some(tm) = spec.types.get(type_name) {
        if tm.newtype.unwrap_or(false) {
            type_name.to_string()
        } else if let Some(ts) = &tm.typescript {
            ts.clone()
        } else {
            type_name.to_string()
        }
    } else {
        match type_name {
            "string" => "string".to_string(),
            "f64" | "decimal" | "u32" | "i64" | "u64" => "number".to_string(),
            "bool" => "boolean".to_string(),
            "date" | "datetime" => "string".to_string(),
            "url" => "string".to_string(),
            other => other.to_string(),
        }
    };

    if nullable {
        format!("{} | null", resolved)
    } else {
        resolved
    }
}

fn is_enum_type(type_name: &str, spec: &ApiSpec) -> bool {
    spec.enums.contains_key(type_name)
}

// ── package.json ─────────────────────────────────────────────────────

fn generate_package_json(spec: &ApiSpec) -> String {
    let name = package_name(spec);
    format!(
        r#"{{
  "name": "{}-sdk",
  "version": "0.1.0",
  "description": "Auto-generated SDK for {}",
  "main": "dist/client.js",
  "types": "dist/client.d.ts",
  "scripts": {{
    "build": "tsc",
    "test": "jest"
  }},
  "dependencies": {{
    "axios": "^1.6.0",
    "cheerio": "^1.0.0-rc.12"
  }},
  "devDependencies": {{
    "@types/cheerio": "^0.22.35",
    "typescript": "^5.3.0"
  }}
}}
"#,
        name, spec.name
    )
}

// ── tsconfig.json ────────────────────────────────────────────────────

fn generate_tsconfig(_spec: &ApiSpec) -> String {
    r#"{
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "lib": ["ES2020"],
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "dist", "**/*.test.ts"]
}
"#
    .to_string()
}

// ── types.ts ─────────────────────────────────────────────────────────

fn generate_types(spec: &ApiSpec) -> String {
    let mut o = String::from("// @generated by webspec — DO NOT EDIT\n\n");

    for (name, mapping) in &spec.types {
        if mapping.newtype.unwrap_or(false) {
            let ts_type = mapping.typescript.as_deref().unwrap_or("number");
            o.push_str(&format!("export type {} = {};\n\n", name, ts_type));
        }
    }

    for (name, enum_def) in &spec.enums {
        let variants: Vec<String> = enum_def
            .values
            .keys()
            .map(|v| format!("  \"{}\"", v))
            .collect();
        o.push_str(&format!(
            "export type {} =\n{};\n\n",
            name,
            variants.join(" |\n")
        ));
    }

    o
}

// ── models.ts ────────────────────────────────────────────────────────

fn generate_models(spec: &ApiSpec) -> String {
    let mut o = String::from("// @generated by webspec — DO NOT EDIT\n\n");

    for (name, entity) in &spec.entities {
        if let Some(fields) = &entity.fields {
            o.push_str(&format!("export interface {} {{\n", name));
            for (field_name, field_def) in fields {
                let ts_type = resolve_type_ts(&field_def.r#type, field_def.nullable.unwrap_or(false), spec);
                o.push_str(&format!("  {}: {};\n", camel_case(field_name), ts_type));
            }
            o.push_str("}\n\n");
        }
    }

    o
}

// ── parser.ts ────────────────────────────────────────────────────────

fn generate_parser(spec: &ApiSpec) -> String {
    let mut o = String::from("// @generated by webspec — DO NOT EDIT\n\n");
    o.push_str("import * as cheerio from 'cheerio';\n\n");

    for (page_name, page_def) in &spec.pages {
        let entity_name = &page_def.entity;
        if let Some(entity) = spec.entities.get(entity_name) {
            if let Some(fields) = &entity.fields {
                let is_list = page_def.list_selector.is_some();
                let return_type = if is_list {
                    format!("{}[]", entity_name)
                } else {
                    entity_name.to_string()
                };

                o.push_str(&format!(
                    "export function parse{}(html: string): {} {{\n",
                    pascal_case(page_name),
                    return_type
                ));
                o.push_str("  const $ = cheerio.load(html);\n");

                if let Some(list_selector) = &page_def.list_selector {
                    o.push_str(&format!(
                        "  const items: {}[] = [];\n",
                        entity_name
                    ));
                    o.push_str(&format!(
                        "  $('{}').each((_: number, el: cheerio.Element) => {{\n",
                        list_selector
                    ));
                    o.push_str("    const $el = $(el);\n");
                    o.push_str(&format!("    const item: {} = {{\n", entity_name));

                    for (field_name, field_def) in fields {
                        let extraction =
                            generate_ts_extraction(field_name, field_def, spec);
                        o.push_str(&format!("      {},\n", extraction));
                    }

                    o.push_str("    };\n");
                    o.push_str("    items.push(item);\n");
                    o.push_str("  });\n");
                    o.push_str("  return items;\n");
                } else {
                    o.push_str(&format!("  const item: {} = {{\n", entity_name));
                    for (field_name, field_def) in fields {
                        let extraction =
                            generate_ts_extraction(field_name, field_def, spec);
                        o.push_str(&format!("    {},\n", extraction));
                    }
                    o.push_str("  };\n");
                    o.push_str("  return item;\n");
                }

                o.push_str("}\n\n");
            }
        }
    }

    o
}

fn generate_ts_extraction(
    field_name: &str,
    field_def: &crate::spec::FieldDef,
    spec: &ApiSpec,
) -> String {
    let prop = camel_case(field_name);
    let field_type = &field_def.r#type;
    let is_optional = field_def.nullable.unwrap_or(false) || field_type.starts_with("Option<");

    let raw = if let Some(attr) = &field_def.attribute {
        if let Some(sel) = &field_def.selector {
            format!("$el.find('{}').attr('{}')", sel, attr)
        } else {
            format!("$el.attr('{}')", attr)
        }
    } else if let Some(sel) = &field_def.selector {
        format!("$el.find('{}').text().trim()", sel)
    } else {
        if is_optional {
            return format!("{}: undefined", prop);
        }
        return format!("{}: \"\"", prop);
    };

    let inner_type = unwrap_option(field_type);
    let needs_num_conv =
        is_numeric_type(inner_type, spec) || is_newtype_numeric(inner_type, spec);
    let needs_bool_conv = inner_type == "bool";

    if needs_num_conv {
        if is_optional {
            format!("{}: (() {{ const v = {}; return v ? Number(v) : undefined; }})()", prop, raw)
        } else {
            format!("{}: Number({} || '0')", prop, raw)
        }
    } else if needs_bool_conv {
        if is_optional {
            format!("{}: (() {{ const v = {}; return v ? v !== 'false' : undefined; }})()", prop, raw)
        } else {
            format!("{}: ({} || 'false') !== 'false'", prop, raw)
        }
    } else if is_enum_type(inner_type, spec) {
        if is_optional {
            format!("{}: ({} || undefined) as {} | undefined", prop, raw, inner_type)
        } else {
            format!("{}: ({} || '') as {}", prop, raw, inner_type)
        }
    } else if is_optional {
        format!("{}: {} || undefined", prop, raw)
    } else {
        format!("{}: {}", prop, raw)
    }
}

fn unwrap_option(type_name: &str) -> &str {
    if type_name.starts_with("Option<") && type_name.ends_with('>') {
        return &type_name[7..type_name.len() - 1];
    }
    type_name
}

fn is_numeric_type(type_name: &str, spec: &ApiSpec) -> bool {
    if let Some(tm) = spec.types.get(type_name) {
        if let Some(ts) = &tm.typescript {
            return ts == "number";
        }
    }
    matches!(type_name, "f64" | "u32" | "i64" | "u64" | "decimal")
}

fn is_newtype_numeric(type_name: &str, spec: &ApiSpec) -> bool {
    if let Some(tm) = spec.types.get(type_name) {
        if tm.newtype.unwrap_or(false) {
            if let Some(ts) = &tm.typescript {
                return ts == "number";
            }
        }
    }
    false
}

// ── client.ts ────────────────────────────────────────────────────────

fn generate_client(spec: &ApiSpec) -> String {
    let client = client_name(spec);
    let base_url = spec.base_url.as_deref().unwrap_or("https://example.com");

    let mut o = String::from("// @generated by webspec — DO NOT EDIT\n\n");
    o.push_str("import axios, { AxiosInstance } from 'axios';\n");
    o.push_str("import * as cheerio from 'cheerio';\n");
    o.push_str(&format!(
        "import {{ {} }} from './types';\n",
        spec.enums
            .keys()
            .map(|k| pascal_case(k))
            .collect::<Vec<_>>()
            .join(", ")
    ));
    o.push_str(&format!(
        "import {{ {} }} from './models';\n",
        spec.entities.keys().map(|k| pascal_case(k)).collect::<Vec<_>>().join(", ")
    ));
    o.push_str("import * as parsers from './parser';\n\n");

    o.push_str(&format!("export class {} {{\n", client));
    o.push_str("  private http: AxiosInstance;\n\n");

    o.push_str(&format!("  constructor(baseUrl: string = '{}') {{\n", base_url));
    o.push_str("    this.http = axios.create({\n");
    o.push_str("      baseURL: baseUrl,\n");
    o.push_str("      timeout: 30000,\n");
    o.push_str("      headers: {\n");
    o.push_str("        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',\n");
    o.push_str("      },\n");
    o.push_str("    });\n");
    o.push_str("  }\n\n");

    o.push_str("  async get(path: string): Promise<string> {\n");
    o.push_str("    const resp = await this.http.get(path);\n");
    o.push_str("    return resp.data;\n");
    o.push_str("  }\n\n");

    for (page_name, page_def) in &spec.pages {
        let url_pattern = page_def.url_pattern.as_ref().or(page_def.url.as_ref());
        if let Some(url_pattern) = url_pattern {
            let params = extract_url_params(url_pattern);
            let entity_name = &page_def.entity;
            let is_list = page_def.list_selector.is_some();
            let method_name = format!("fetch{}", pascal_case(page_name));

            let params_str = if params.is_empty() {
                String::new()
            } else {
                params
                    .iter()
                    .map(|p| format!("{}: number", camel_case(p)))
                    .collect::<Vec<_>>()
                    .join(", ")
            };

            let return_type = if is_list {
                format!("{}[]", entity_name)
            } else {
                entity_name.to_string()
            };

            o.push_str(&format!(
                "  async {}({}): Promise<{}> {{\n",
                method_name, params_str, return_type
            ));

            let mut url_str = url_pattern.clone();
            for p in &params {
                url_str = url_str.replace(
                    &format!("{{{}}}", p),
                    &format!("${{{}}}", camel_case(p)),
                );
            }

            o.push_str(&format!(
                "    const html = await this.get(`{}`);\n",
                url_str
            ));
            o.push_str(&format!(
                "    return parsers.parse{}(html);\n",
                pascal_case(page_name)
            ));
            o.push_str("  }\n\n");
        }
    }

    o.push_str("}\n");
    o
}

fn extract_url_params(pattern: &str) -> Vec<String> {
    let mut params = Vec::new();
    let mut chars = pattern.chars().peekable();
    while let Some(c) = chars.next() {
        if c == '{' {
            let mut param = String::new();
            while let Some(&nc) = chars.peek() {
                if nc == '}' {
                    chars.next();
                    break;
                }
                param.push(nc);
                chars.next();
            }
            params.push(param);
        }
    }
    params
}
